### ISSUE TITLE
Improve Performance of ILinePlot

### ISSUE THREAD

**Issue by sinkap** [ARM-software/trappy#103]
The performance of ILinePlot currently bottlenecks on the function 

```ILinePlot.convertToDataTable in ILinePlot.js```

![bottleneck](https://cloud.githubusercontent.com/assets/2152812/11745335/61807846-a00f-11e5-8fc3-7977b43d9dbb.png)

We can avoid this overhead by doing this conversion in python.

**Comment by John-P** [comment]
When plotting really large data sets I had some issues even when converted in python. However (this site)[http://kaliatech.github.io/dygraphs-dynamiczooming-example/] has some information about plotting really large datasets.

**Comment by sinkap** [comment]
Thanks @John-P Will give this a read :+1:

**Comment by JaviMerino** [comment]
Fixed by fea80b84fa13a9c0ce75be7fe8c01151f813ee0f
