### ISSUE TITLE
Multitrace multicolumn plots don't display the correct title on top of each graph

### ISSUE THREAD

**Issue by JaviMerino** [ARM-software/trappy#168]
See the last plot of `doc/Plotter.ipynb`.  The titles used to be "Trace 0" and "Trace 1".  If you execute it now you get just ".".

![trappy_issue](https://cloud.githubusercontent.com/assets/44926/14203070/aafee8c2-f7f3-11e5-8699-c823e258edee.png)

**Comment by mdigiorgio** [comment]
Interesting! I'll have look at it...
