### ISSUE TITLE
Install  issues :   SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.

### ISSUE THREAD

**Issue by zuozhengkun** [ARM-software/trappy#172]
Hello,
  Need  your   help.
I  install  the   package  numpy-1.9.3  or   pandas-0.18.0 ,  trappy,    
my  python version  is   : python --version
Python 2.7.3

But  here  it  happens  some  issues  as below:
 SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.
     ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Gk4B_J/pandas/

How to handle  it, or  give  some  solutions  of  website.

Thanks.

**Comment by zuozhengkun** [comment]
I  tried some  packages  for  it,  but  failed  yet.

**Comment by zuozhengkun** [comment]
~/Documents/EAS/trappy$ sudo apt-get install python-dev

Failed to fetch http://mirrors.sohu.com/ubuntu/pool/main/o/openssl/libssl-doc_1.0.1-4ubuntu5.31_all.deb  404  Not Found
Failed to fetch http://mirrors.sohu.com/ubuntu/pool/main/p/python2.7/python2.7-dev_2.7.3-0ubuntu3.6_amd64.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by zuozhengkun** [comment]
Hello,
  After the above  issues resolved,  then  new  issue, 
   ipython notebook  
   ImportError: No module named html.notebook.notebookapp

  Why ?
  how to do it.

  Thx.

**Comment by zuozhengkun** [comment]
Hello,
  After the above  issues resolved,  then  new  issue, 
   ipython notebook  
   ImportError: No module named html.notebook.notebookapp

  Why ?
  how to do it.

  Thx.

**Comment by zuozhengkun** [comment]
trappy$ sudo ipython notebook Untitled0.ipynb
/usr/local/lib/python2.7/dist-packages/IPython/utils/traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  warn("IPython.utils.traitlets has moved to a top-level traitlets package.")
Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 9, in <module>
    load_entry_point('ipython==0.13.1', 'console_scripts', 'ipython')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2542, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2202, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2208, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/IPython/frontend/terminal/ipapp.py", line 53, in <module>
    from IPython.utils.path import get_ipython_dir, check_for_old_config
ImportError: cannot import name check_for_old_config

**Comment by JaviMerino** [comment]
It looks like you are having lots of issues installing ipython.  The last message you reference looks like a bad IPython installation.  Let's start from the beginning, which Linux distribution are you using?

**Comment by zuozhengkun** [comment]
or i got it.
Need to install the ipython
sudo pip install ipython==0.13.1
pip install -U ipython

**Comment by zuozhengkun** [comment]
Yes,  it is  Linux  ubutun OS,
 line  %matplotlib inline  is  replaced by    %pylab inline 
/usr/local/lib/python2.7/dist-packages/pandas-0.18.0-py2.7-linux-x86_64.egg/pandas/computation/__init__.py:25: UserWarning: The installed version of numexpr 1.4.2 is not supported in pandas and will be not be used
The minimum supported version is 2.1

  "version is 2.1\n".format(ver=ver), UserWarning)

But failed it .

Thanks.

**Comment by zuozhengkun** [comment]
sudo pip install --upgrade pandas

Not  effect.

**Comment by mdigiorgio** [comment]
Try to follow the instructions on [How to install TRAPpy](https://github.com/ARM-software/trappy/#installation). But first, try to remove them from your system.

Do not execute the last step (i.e. `sudo pip install --upgrade trappy`) if you plan to clone the repository.

**Comment by zuozhengkun** [comment]
Basically  i   confirmed  to the guide  How to install TRAPpy
and download  some  patches.
 
UserWarning: The installed version of numexpr 1.4.2 is not supported in pandas and will be not be used
The minimum supported version is 2.1

**Comment by mdigiorgio** [comment]
Have you tried with `sudo pip install numexpr`?

**Comment by zuozhengkun** [comment]
Yes,  i  did these steps  as  above,
But run ...



OK;
the above pass through.
But prompt,
ValueError: invalid version number '1.1.1rc'

Thanks.

**Comment by zuozhengkun** [comment]
In [2]:

%pylab inline

import trappy


Welcome to pylab, a matplotlib-based Python environment [backend: module://IPython.zmq.pylab.backend_inline].
For more information, type 'help(pylab)'.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-0110ba429caf> in <module>()
      1 get_ipython().magic(u'pylab inline')
----> 2 import trappy

**Comment by zuozhengkun** [comment]
%matplotlib inline  ---> replaced  by   %pylab inline

**Comment by zuozhengkun** [comment]
else  more than  one line:
ERROR: Line magic function `%matplotlib` not found.

**Comment by JaviMerino** [comment]
that sounds like an error in your ipython, which version of ipython do you have?  You can check it by running: `python -c "import IPython; print IPython.__version__"`.  Also, you mentioned that you have ubuntu but you didn't say which version, what's the output of `lsb_release -a`?

**Comment by zuozhengkun** [comment]
1. SPREADTRUM\zhengkun.zuo@zkzubtpc:~/Documents/EAS/trappy$ python -c "import IPython; print IPython.__version__"
0.13.1

2.  lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.2 LTS
Release:	12.04
Codename:	precise

Thanks.

**Comment by JaviMerino** [comment]
Ubuntu 12.04 explains why you have so many problems and so much outdated software.

`ERROR: Line magic function %matplotlib not found` is because you have an old ipython (0.13.1).  The following should give you the latest ipython:
```
apt-get remove ipython
pip install ipython\[notebook\]
```

**Comment by zuozhengkun** [comment]
Hello,
 done  as  what  your  said,
but :
SPREADTRUM\zhengkun.zuo@zkzubtpc:~/Documents/EAS/trappy/trappy/doc$ ipython --version
0.13.1

and  ipython notebook  issue  encounters  yet .

and  I  run WA tool, side effect problems.
 sudo wa -h
/usr/lib/pymodules/python2.7/matplotlib/__init__.py:923: UserWarning:  This call to matplotlib.use() has no effect
because the the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

Thanks.

**Comment by zuozhengkun** [comment]
I done it:

sudo apt-get  autoremove ipython
sudo pip install ipython notebook

Are they  correct ?

**Comment by JaviMerino** [comment]
> sudo apt-get autoremove ipython

It's `remove` not `autoremove`.

After `pip install --upgrade ipython\[all\]`, the version of ipython should be 4.1.2 (or close to it):
```
$ python -c "import IPython; print IPython.__version__"
4.1.2
```

It looks like you are struggling with installing python packages.  Maybe you should familiarize yourself with pip, ipython (and how to install it) and probably virtualenv as well.

**Comment by zuozhengkun** [comment]
Yes,
 I  touched  this ipython tool  for  a  short time.

Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x25089d0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/traitlets/

Maybe network  is  badly...

**Comment by mdigiorgio** [comment]
> Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError(': Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/traitlets/

> Maybe network is badly...

This is not related to trappy. In fact, trappy doesn't need any connection, it's a visualization tool. Please raise it on the relevant issue tracker. Also, I suggest you to use stackoverflow in addition to what was suggested by @JaviMerino. Hope it helps...

**Comment by zuozhengkun** [comment]
yes,
python -c "import IPython; print IPython.__version__"
4.1.2

:~/Documents/EAS/trappy/trappy/doc$ ipython notebook
[TerminalIPythonApp] WARNING | Subcommand `ipython notebook` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter notebook`... continue in 5 sec. Press Ctrl-C to quit now.
/usr/local/lib/python2.7/dist-packages/IPython/paths.py:54: UserWarning: Moving ~/.config/ipython to ~/.ipython
  warn('Moving {0} to {1}'.format(cu(xdg_ipdir), cu(ipdir)))
[I 20:00:51.900 NotebookApp] Writing notebook server cookie secret to /home/likewise-open/SPREADTRUM/zhengkun.zuo/.local/share/jupyter/runtime/notebook_cookie_secret
[W 20:00:51.908 NotebookApp] ipywidgets package not installed.  Widgets are unavailable.
[I 20:00:51.914 NotebookApp] Serving notebooks from local directory: /home/likewise-open/SPREADTRUM/zhengkun.zuo/Documents/EAS/trappy/trappy/doc
[I 20:00:51.914 NotebookApp] 0 active kernels 
[I 20:00:51.914 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/

and pop  warning...

in addition,
SPREADTRUM\zhengkun.zuo@zkzubtpc:/usr$ sudo wa run  -c myconfig.py -f  ipa_tuning_practical_1_antutu.yaml 
/usr/lib/pymodules/python2.7/matplotlib/__init__.py:923: UserWarning:  This call to matplotlib.use() has no effect
because the the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

**Comment by zuozhengkun** [comment]
need  to  " sudo pip install ipython[notebook]"   ?

**Comment by zuozhengkun** [comment]
http://stackoverflow.com/questions/16170989/matplotlib-remove-warning-about-matplotlib-use  
this  is  one  solution ?

**Comment by JaviMerino** [comment]
I think you can ignore that warning.

**Comment by zuozhengkun** [comment]
yes,  i  can ignore  this  info : This call to matplotlib.use() has no effect
because the the backend has already been chosen;

But point 1:
SPREADTRUM\zhengkun.zuo@zkzubtpc:~/Documents/EAS/trappy/trappy/doc$ ipython notebook
[TerminalIPythonApp] WARNING | Subcommand `ipython notebook` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter notebook`... continue in 5 sec. Press Ctrl-C to quit now.
[W 09:55:18.614 NotebookApp] ipywidgets package not installed.  Widgets are unavailable.
[I 09:55:18.619 NotebookApp] Serving notebooks from local directory: /home/likewise-open/SPREADTRUM/zhengkun.zuo/Documents/EAS/trappy/trappy/doc
[I 09:55:18.619 NotebookApp] 0 active kernels 
[I 09:55:18.619 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 09:55:18.619 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 09:55:23.670 NotebookApp] Notebook Dynamic traces.ipynb is not trusted

point 2:
SPREADTRUM\zhengkun.zuo@zkzubtpc:~/Documents/EAS/trappy/trappy/doc$ ipython notebook
[TerminalIPythonApp] WARNING | Subcommand `ipython notebook` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter notebook`... continue in 5 sec. Press Ctrl-C to quit now.
[W 09:55:18.614 NotebookApp] ipywidgets package not installed.  Widgets are unavailable.
[I 09:55:18.619 NotebookApp] Serving notebooks from local directory: /home/likewise-open/SPREADTRUM/zhengkun.zuo/Documents/EAS/trappy/trappy/doc
[I 09:55:18.619 NotebookApp] 0 active kernels 
[I 09:55:18.619 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 09:55:18.619 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 09:55:23.670 NotebookApp] Notebook Dynamic traces.ipynb is not trusted
[W 09:55:23.683 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20160407095518 (127.0.0.1) 5.31ms referer=http://localhost:8888/notebooks/Dynamic%20traces.ipynb
[I 09:55:24.275 NotebookApp] Kernel started: bfab573c-74d7-4336-99a3-976712c1c79f
[I 09:57:24.232 NotebookApp] Saving file at /Dynamic traces.ipynb
[W 09:57:24.232 NotebookApp] Saving untrusted notebook Dynamic traces.ipynb

Would   both of  them  warning info  not   affect   the  end   running  result?
Or  also   can  be  ignored .

You  are  always  kind   to   us.

Thanks.

**Comment by JaviMerino** [comment]
> [TerminalIPythonApp] WARNING | Subcommand ipython notebook is deprecated and will be removed in future versions.
> [TerminalIPythonApp] WARNING | You likely want to use jupyter notebook... continue in 5 sec. Press Ctrl-C to quit now.

That's ok.  In the future you can run `jupyter notebook` instead of `ipython notebook`.  Both will work.

> [W 09:55:23.670 NotebookApp] Notebook Dynamic traces.ipynb is not trusted

This is ok.  So yes, the warnings can be ignored.

**Comment by zuozhengkun** [comment]
OK,
thank you very much.

**Comment by Anu-Premkumar** [comment]
> Hello,
> Need your help.
> I install the package numpy-1.9.3 or pandas-0.18.0 , trappy,
> my python version is : python --version
> Python 2.7.3
> 
> But here it happens some issues as below:
> SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.
> ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Gk4B_J/pandas/
> 
> How to handle it, or give some solutions of website.
> 
> Thanks.

Hi Can you please tell me how this issue got resolved? Im also facing the same issue with python 2.6.6

**Comment by douglas-raillard-arm** [comment]
Hi @Anu-Premkumar,

I don't know the specific details of the error you face but your setup is outdated and very unlikely to work anyway, since Python 2.6.6 did not receive security maintenance since 2013 [1], and Pandas now mandates Python >= 3.5.3 [2].

Also, I highly recommend installing the package by going into the root of trappy repository and calling `pip install .` rather than invoking setup.py manually [3]. I would also recommend moving away from Python 2 ASAP, since it's days are now counted and some packages (like pandas or matplotlib) only work in Python 3 [4].

[1] https://www.python.org/downloads/release/python-266/
[2] https://pypi.org/project/pandas/
[3] https://stackoverflow.com/questions/15724093/difference-between-python-setup-py-install-and-pip-install
[4] https://pythonclock.org/
