### ISSUE TITLE
Make trappy::Base()'s parse raw traces by default

### ISSUE THREAD

**Issue by JaviMerino** [ARM-software/trappy#210]
`trappy::Base()` started parsing the normal output of trace-cmd because it includes parsed arrays.  When the `sched_switch` event was introduced, we added raw parsing because for some events we don't want the additional "prettifying" that trace-cmd does and we just want the raw values of the trace.  Right now, parsing the raw trace file needs to be explicitly specified, and is only done for `sched_wakeup`, `sched_wakeup_new` and `sched_switch`.  If you are parsing a trace with `sched_switch` and `cpu_frequency` events, then trappy parses two files: `trace.txt` for `cpu_frequency` and `trace.raw.txt` for `sched_switch`.  Arguably, both events could be parsed from the raw trace.  It's better to switch to parsing raw traces by default and only have trappy create the trace.txt when it's parsing events that need it.

**Comment by JaviMerino** [comment]
Suggested by @derkling

**Comment by sinkap** [comment]
Merged #253 which fixes this. Thanks @credp!
