### ISSUE TITLE
test_copyright should ignore files in .gitignore

### ISSUE THREAD

**Issue by sinkap** [ARM-software/trappy#22]
test_copyright should consider files in .gitignore before walking the directory. This is needed for the _build directory in the new API docs which is a part of .gitignore

**Comment by JaviMerino** [comment]
That's why we were using `git ls-files` :wink:. I guess we'll have to replicate that part of the functionality.

**Comment by sinkap** [comment]
Ahh!! Then my patch needs to be augmented. Thanks! Will add this bit as
well.

On Fri, Sep 11, 2015 at 2:20 PM, Javi Merino <notifications@github.com>
wrote:

> That's why we were using git ls-files [image: :wink:]. I guess we'll have
> to replicate that part of the functionality.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ARM-software/trappy/issues/22#issuecomment-139544112>.
>



-- 
Regards,
Kapileshwar Singh(KP)

**Comment by sinkap** [comment]
Fixed by #33
