### ISSUE TITLE
Remove legacy from trappy/__init__.py

### ISSUE THREAD

**Issue by bjackman** [ARM-software/trappy#233]
There's some code marked "For backwards compatibility.  Remove by 2016-12-31" in `trappy/__init__.py`.

So let's remove it?

**Comment by JaviMerino** [comment]
#234 is merged, so closing

**Comment by bjackman** [comment]
Cheers. I was under the impression this would auto-close when the PR was merged.

**Comment by JaviMerino** [comment]
You need to say "fixes" before the issue number: https://github.com/blog/1506-closing-issues-via-pull-requests

I believe there are other magic words.  I think I've closed issues with just "fix" or "close" or something like that.
