### ISSUE TITLE
Interactive plots in shared/external notebooks

### ISSUE THREAD

**Issue by bjackman** [ARM-software/trappy#239]
It would be really useful to be able to share notebooks with interactive trappy plots via systems like [nbviewer](http://nbviewer.jupyter.org/). 

Should investigate how the nbextension system works and if there's a way to get the trappy JS into externally shared notebooks. 

If it's not possible via that mechanism then maybe notebooks can be exported as HTML with all the JS inline?

**Comment by JaviMerino** [comment]
Have you tried the method described in `doc/InteractivePlotter`, in Section "Exporting notebooks with interactive plots to HTML" (at the bottom)?  If I understand it correctly, this is what you are asking for.

**Comment by bjackman** [comment]
No I had not noticed that, thanks for pointing it out! Will close this issue once I get around to trying it.

**Comment by bjackman** [comment]
Thanks!
