### ISSUE TITLE
[FEATURE] Add an inline help for trace plotter

### ISSUE THREAD

**Issue by derkling** [ARM-software/trappy#52]
It could be useful to present the user a simple help screen for example when the 'h' key is pressed while the focus is on the plot.
Something similar to the Jupyter Notebook online help, which lists all the keyboard/mouse short-cut available to interact with the plotter.

Maybe it could be challenging to trigger the visualization on a key press, in that case a different approach could be to just display a small "question mark / help / guide" button (maybe top-right corner, in the info window) which display the afore described help menu.

**Comment by sinkap** [comment]
This is something that we will add for sure. Thanks for the feedback @derkling :+1:

**Comment by JaviMerino** [comment]
Merged as #66
