### ISSUE TITLE
[FEATURE] Extend Run object constructor to get a list of custom events

### ISSUE THREAD

**Issue by derkling** [ARM-software/trappy#69]
The FTrace module provided by devlib allows the user to specify a simple list of events to be collected via FTrace. These events and only them are usually the interesting events for the following analysis.

For that reason, the support in Run() for a new "custom" scope could be useful to better match the devlib API. A new parameter "events" should allows to dynamically register at Run() object construction time only the list of events specified by the user.

This is expected to optimize memory and parsing time, while also solving some handshakes due to mixed usage of pre-defined and dynamically registered events.

**Comment by derkling** [comment]
I've noticed that some events (e.g.  sched_switch) require a raw trace.
Scheduler switching events are always parsed by trappy to support the trace plotting API, thus it make sense to keep it pre-registered.

However, in general, if we want to introduce a new support for "list based" events definition we should also think about a convenient way to defined which events are to be parsed from the raw trace and which can be parsed from the "formatted" trace.

**Comment by JaviMerino** [comment]
We could register the existing `trappy` class for things like `sched_switch` instead of doing a `register_dynamic`.  That should take care of the raw traces that `trappy` already knows about.  For those that `trappy` doesn't know about you'll have to register them yourself before as usual.

**Comment by derkling** [comment]
The proposed implementation matches my expectations. Thanks. Looking forward to see it merged.
