### ISSUE TITLE
[FEATURE] LinePlotter: add "event:colum" based specification of signals to plot

### ISSUE THREAD

**Issue by derkling** [ARM-software/trappy#79]
Now that we have synchronized events name with dataset names, it could be useful to simplify the LinePlot interface by adding a new way to specify "templates" and "columns".

A new parameter "events" should accept a list of "event:column" specifications, e.g. 

    signals_to_plot = ['my_event1:col1_1', 'my_event2:col2_1', 'my_event2:col2_2']
    trappy.LinePlot(run, events=signals_to_plot)

This new single parameter can be "expanded" internally to get the same behaviours of the current API, which requires:

    templates = [run.my_event1,  run.my_event2, ,  run.my_event2]
    column = ['col1_1', 'col1_1', 'col1_2']
    trappy.LinePlot(run, templates, column=column)

**Comment by sinkap** [comment]
Submitted pull request #81

**Comment by JaviMerino** [comment]
Merged as #81
